name: Build

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:

    - uses: actions/checkout@v4

    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x

    - name: Restore
      run: dotnet restore SpecBalance/SpecBalance.csproj

    - name: Build
      run: dotnet build SpecBalance/SpecBalance.csproj -c Release --no-restore

    - uses: actions/upload-artifact@v4
      with:
        name: SpecBalance
        path: SpecBalance/bin/Release/net6.0/SpecBalance.dll
